---
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:solid/typescript
  - plugin:import/recommended
  - plugin:import/typescript
plugins:
  - import
  - solid
settings:
  import/ignore:
    - node_modules
    - \\.json$
  import/extensions:
    - .js
    - .jsx
    - .ts
    - .tsx
rules:
  import/no-unresolved: 0 # turning off for now. Can't resolve types
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/imports-first: 2
  import/no-duplicates: 2
  import/newline-after-import: 2
