---
version: '3.4'

services:
  db:
    container_name: nov8_db
    image: postgres
    env_file: .env

  migrate:
    container_name: nov8_migrate
    stdin_open: true
    build:
      context: client
      dockerfile: client.Dockerfile
      target: migrate
    volumes:
      - ./client:/root
    env_file: .env
    depends_on:
      - db
